# Generated by Django 3.2 on 2022-04-25 10:44

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Зоголовок')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='media/images/')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='', verbose_name='Книга')),
                ('name', models.CharField(max_length=255, verbose_name='Имя книга')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='media/images/')),
                ('description', models.CharField(max_length=255, verbose_name='Описания')),
                ('created', models.DateField(auto_now=True)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.booktypesmodel')),
            ],
        ),
    ]
